'use client';

import { useEffect } from 'react';

/**
 * Service Worker Unregistration Component
 *
 * Purpose: Remove incompatible service worker generated by vite-plugin-pwa
 *
 * Context:
 * - vite-plugin-pwa was incorrectly included in Next.js project (Vite-only package)
 * - Generated service worker causing "no-response" errors in console
 * - Service worker tried to cache routes that redirect due to auth middleware
 *
 * This component runs once on app load to clean up existing registrations
 * from users' browsers. Can be removed after all users have visited the app.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration
 */
export function UnregisterServiceWorker() {
  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      navigator.serviceWorker.getRegistrations().then((registrations) => {
        if (registrations.length > 0) {
          registrations.forEach((registration) => {
            registration.unregister().then((success) => {
              if (success) {
                console.log('[SW] Service worker unregistered successfully');
              }
            });
          });
        }
      });
    }
  }, []);

  return null;
}
